### ISSUE TITLE
name the schema

### ISSUE THREAD

**Issue by matthewmueller** [standardschema/javascript#30]
Providing an optional name for the schema could be handy when you have larger applications. Right now the validation error I get back doesn't help me pinpoint which schema has the error:

``` js
{ MultiError: Validation failed for "String#pattern" at "time"
    at /Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/index.js:27:51
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
    at Function.Module.runMain (module.js:577:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/async-to-gen/async-node:98:10)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
  cause: undefined,
  errors:
   [ { ValidationError: Validation failed for "String#pattern" at "time"
         at Object.error (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/index.js:18:23)
         at /Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/types/string.js:83:27
         at /Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:75:32
         at dispatch (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:74:20)
         at next (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:76:28)
         at isString (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/types/string.js:47:12)
         at /Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:75:32
         at dispatch (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:74:20)
         at next (/Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/utils.js:76:28)
         at /Users/matt/Projects/standupjack.com/node_modules/jaywalk/dist/types/any.js:73:16
       cause: undefined,
       path: [Object],
       type: 'String',
       keyword: 'pattern',
       assertion: '^\\d{1,2}:\\d{1,2}$',
       value: '1030' } ] }
```

**Comment by blakeembrey** [comment]
Sounds great. What I actually think I want to do is "tag" schema objects with an id soon. There's a bit of a refactor I have in my head to make this work fantastically and with some cool existing technologies.
